PROG = stl-rb

LOCAL_OBJS = src/rbtree.o src/test.o
LOCAL_CFLAGS = -D_RB_RELEASE -std=c++11 -fopenmp -pthread
LOCAL_CXXFLAGS = -D_RB_RELEASE -std=c++11 -fopenmp -pthread

# Let the top-level Makefile handle build/test rules
include ../Makefile

